import 'dart:math' as math;

import 'exercise_metadata.dart';

enum MuscleSurface3D { front, back, left, right }

class MusclePatch3DSpec {
  const MusclePatch3DSpec({
    required this.id,
    required this.region,
    required this.surface,
    required this.x,
    required this.y,
    required this.z,
    required this.width,
    required this.height,
    this.tilt = 0,
  });

  final String id;
  final MuscleRegion region;
  final MuscleSurface3D surface;
  final double x;
  final double y;
  final double z;
  final double width;
  final double height;
  final double tilt;
}

class MuscleRegion3DMapping {
  const MuscleRegion3DMapping({
    required this.region,
    required this.visualRegionIds,
    required this.preferredYaw,
  });

  final MuscleRegion region;
  final List<String> visualRegionIds;
  final double preferredYaw;
}

const musclePatch3DSpecs = <MusclePatch3DSpec>[
  MusclePatch3DSpec(
    id: 'upperChest.left',
    region: MuscleRegion.upperChest,
    surface: MuscleSurface3D.front,
    x: -0.17,
    y: -0.78,
    z: 0.25,
    width: 0.30,
    height: 0.18,
    tilt: -0.08,
  ),
  MusclePatch3DSpec(
    id: 'upperChest.right',
    region: MuscleRegion.upperChest,
    surface: MuscleSurface3D.front,
    x: 0.17,
    y: -0.78,
    z: 0.25,
    width: 0.30,
    height: 0.18,
    tilt: 0.08,
  ),
  MusclePatch3DSpec(
    id: 'midChest.left',
    region: MuscleRegion.midChest,
    surface: MuscleSurface3D.front,
    x: -0.17,
    y: -0.58,
    z: 0.27,
    width: 0.32,
    height: 0.24,
  ),
  MusclePatch3DSpec(
    id: 'midChest.right',
    region: MuscleRegion.midChest,
    surface: MuscleSurface3D.front,
    x: 0.17,
    y: -0.58,
    z: 0.27,
    width: 0.32,
    height: 0.24,
  ),
  MusclePatch3DSpec(
    id: 'lowerChest.left',
    region: MuscleRegion.lowerChest,
    surface: MuscleSurface3D.front,
    x: -0.16,
    y: -0.40,
    z: 0.25,
    width: 0.27,
    height: 0.13,
  ),
  MusclePatch3DSpec(
    id: 'lowerChest.right',
    region: MuscleRegion.lowerChest,
    surface: MuscleSurface3D.front,
    x: 0.16,
    y: -0.40,
    z: 0.25,
    width: 0.27,
    height: 0.13,
  ),
  MusclePatch3DSpec(
    id: 'lats.left',
    region: MuscleRegion.lats,
    surface: MuscleSurface3D.back,
    x: -0.23,
    y: -0.42,
    z: -0.25,
    width: 0.29,
    height: 0.49,
    tilt: 0.05,
  ),
  MusclePatch3DSpec(
    id: 'lats.right',
    region: MuscleRegion.lats,
    surface: MuscleSurface3D.back,
    x: 0.23,
    y: -0.42,
    z: -0.25,
    width: 0.29,
    height: 0.49,
    tilt: -0.05,
  ),
  MusclePatch3DSpec(
    id: 'upperBack.left',
    region: MuscleRegion.upperBack,
    surface: MuscleSurface3D.back,
    x: -0.16,
    y: -0.75,
    z: -0.26,
    width: 0.31,
    height: 0.22,
    tilt: 0.08,
  ),
  MusclePatch3DSpec(
    id: 'upperBack.right',
    region: MuscleRegion.upperBack,
    surface: MuscleSurface3D.back,
    x: 0.16,
    y: -0.75,
    z: -0.26,
    width: 0.31,
    height: 0.22,
    tilt: -0.08,
  ),
  MusclePatch3DSpec(
    id: 'midBack',
    region: MuscleRegion.midBack,
    surface: MuscleSurface3D.back,
    x: 0,
    y: -0.45,
    z: -0.28,
    width: 0.25,
    height: 0.40,
  ),
  MusclePatch3DSpec(
    id: 'lowerBack',
    region: MuscleRegion.lowerBack,
    surface: MuscleSurface3D.back,
    x: 0,
    y: -0.14,
    z: -0.25,
    width: 0.43,
    height: 0.22,
  ),
  MusclePatch3DSpec(
    id: 'frontDelts.left',
    region: MuscleRegion.frontDelts,
    surface: MuscleSurface3D.front,
    x: -0.47,
    y: -0.75,
    z: 0.13,
    width: 0.22,
    height: 0.23,
  ),
  MusclePatch3DSpec(
    id: 'frontDelts.right',
    region: MuscleRegion.frontDelts,
    surface: MuscleSurface3D.front,
    x: 0.47,
    y: -0.75,
    z: 0.13,
    width: 0.22,
    height: 0.23,
  ),
  MusclePatch3DSpec(
    id: 'sideDelts.left',
    region: MuscleRegion.sideDelts,
    surface: MuscleSurface3D.left,
    x: -0.53,
    y: -0.74,
    z: 0,
    width: 0.20,
    height: 0.26,
  ),
  MusclePatch3DSpec(
    id: 'sideDelts.right',
    region: MuscleRegion.sideDelts,
    surface: MuscleSurface3D.right,
    x: 0.53,
    y: -0.74,
    z: 0,
    width: 0.20,
    height: 0.26,
  ),
  MusclePatch3DSpec(
    id: 'rearDelts.left',
    region: MuscleRegion.rearDelts,
    surface: MuscleSurface3D.back,
    x: -0.47,
    y: -0.75,
    z: -0.13,
    width: 0.22,
    height: 0.23,
  ),
  MusclePatch3DSpec(
    id: 'rearDelts.right',
    region: MuscleRegion.rearDelts,
    surface: MuscleSurface3D.back,
    x: 0.47,
    y: -0.75,
    z: -0.13,
    width: 0.22,
    height: 0.23,
  ),
  MusclePatch3DSpec(
    id: 'biceps.left',
    region: MuscleRegion.biceps,
    surface: MuscleSurface3D.front,
    x: -0.58,
    y: -0.34,
    z: 0.12,
    width: 0.18,
    height: 0.36,
  ),
  MusclePatch3DSpec(
    id: 'biceps.right',
    region: MuscleRegion.biceps,
    surface: MuscleSurface3D.front,
    x: 0.58,
    y: -0.34,
    z: 0.12,
    width: 0.18,
    height: 0.36,
  ),
  MusclePatch3DSpec(
    id: 'triceps.left',
    region: MuscleRegion.triceps,
    surface: MuscleSurface3D.back,
    x: -0.58,
    y: -0.34,
    z: -0.12,
    width: 0.18,
    height: 0.36,
  ),
  MusclePatch3DSpec(
    id: 'triceps.right',
    region: MuscleRegion.triceps,
    surface: MuscleSurface3D.back,
    x: 0.58,
    y: -0.34,
    z: -0.12,
    width: 0.18,
    height: 0.36,
  ),
  MusclePatch3DSpec(
    id: 'forearms.left.front',
    region: MuscleRegion.forearms,
    surface: MuscleSurface3D.front,
    x: -0.64,
    y: 0.05,
    z: 0.08,
    width: 0.15,
    height: 0.39,
  ),
  MusclePatch3DSpec(
    id: 'forearms.right.front',
    region: MuscleRegion.forearms,
    surface: MuscleSurface3D.front,
    x: 0.64,
    y: 0.05,
    z: 0.08,
    width: 0.15,
    height: 0.39,
  ),
  MusclePatch3DSpec(
    id: 'forearms.left.back',
    region: MuscleRegion.forearms,
    surface: MuscleSurface3D.back,
    x: -0.64,
    y: 0.05,
    z: -0.08,
    width: 0.15,
    height: 0.39,
  ),
  MusclePatch3DSpec(
    id: 'forearms.right.back',
    region: MuscleRegion.forearms,
    surface: MuscleSurface3D.back,
    x: 0.64,
    y: 0.05,
    z: -0.08,
    width: 0.15,
    height: 0.39,
  ),
  MusclePatch3DSpec(
    id: 'quads.left',
    region: MuscleRegion.quads,
    surface: MuscleSurface3D.front,
    x: -0.20,
    y: 0.72,
    z: 0.18,
    width: 0.27,
    height: 0.61,
  ),
  MusclePatch3DSpec(
    id: 'quads.right',
    region: MuscleRegion.quads,
    surface: MuscleSurface3D.front,
    x: 0.20,
    y: 0.72,
    z: 0.18,
    width: 0.27,
    height: 0.61,
  ),
  MusclePatch3DSpec(
    id: 'hamstrings.left',
    region: MuscleRegion.hamstrings,
    surface: MuscleSurface3D.back,
    x: -0.20,
    y: 0.76,
    z: -0.17,
    width: 0.27,
    height: 0.60,
  ),
  MusclePatch3DSpec(
    id: 'hamstrings.right',
    region: MuscleRegion.hamstrings,
    surface: MuscleSurface3D.back,
    x: 0.20,
    y: 0.76,
    z: -0.17,
    width: 0.27,
    height: 0.60,
  ),
  MusclePatch3DSpec(
    id: 'calves.left.front',
    region: MuscleRegion.calves,
    surface: MuscleSurface3D.front,
    x: -0.20,
    y: 1.40,
    z: 0.12,
    width: 0.19,
    height: 0.48,
  ),
  MusclePatch3DSpec(
    id: 'calves.right.front',
    region: MuscleRegion.calves,
    surface: MuscleSurface3D.front,
    x: 0.20,
    y: 1.40,
    z: 0.12,
    width: 0.19,
    height: 0.48,
  ),
  MusclePatch3DSpec(
    id: 'calves.left.back',
    region: MuscleRegion.calves,
    surface: MuscleSurface3D.back,
    x: -0.20,
    y: 1.40,
    z: -0.12,
    width: 0.19,
    height: 0.48,
  ),
  MusclePatch3DSpec(
    id: 'calves.right.back',
    region: MuscleRegion.calves,
    surface: MuscleSurface3D.back,
    x: 0.20,
    y: 1.40,
    z: -0.12,
    width: 0.19,
    height: 0.48,
  ),
  MusclePatch3DSpec(
    id: 'adductors.left',
    region: MuscleRegion.adductors,
    surface: MuscleSurface3D.front,
    x: -0.08,
    y: 0.70,
    z: 0.20,
    width: 0.10,
    height: 0.48,
  ),
  MusclePatch3DSpec(
    id: 'adductors.right',
    region: MuscleRegion.adductors,
    surface: MuscleSurface3D.front,
    x: 0.08,
    y: 0.70,
    z: 0.20,
    width: 0.10,
    height: 0.48,
  ),
  MusclePatch3DSpec(
    id: 'glutes.left',
    region: MuscleRegion.glutes,
    surface: MuscleSurface3D.back,
    x: -0.17,
    y: 0.31,
    z: -0.23,
    width: 0.30,
    height: 0.30,
  ),
  MusclePatch3DSpec(
    id: 'glutes.right',
    region: MuscleRegion.glutes,
    surface: MuscleSurface3D.back,
    x: 0.17,
    y: 0.31,
    z: -0.23,
    width: 0.30,
    height: 0.30,
  ),
  MusclePatch3DSpec(
    id: 'abs',
    region: MuscleRegion.abs,
    surface: MuscleSurface3D.front,
    x: 0,
    y: -0.05,
    z: 0.26,
    width: 0.24,
    height: 0.47,
  ),
  MusclePatch3DSpec(
    id: 'obliques.left',
    region: MuscleRegion.obliques,
    surface: MuscleSurface3D.left,
    x: -0.30,
    y: -0.07,
    z: 0.05,
    width: 0.15,
    height: 0.43,
  ),
  MusclePatch3DSpec(
    id: 'obliques.right',
    region: MuscleRegion.obliques,
    surface: MuscleSurface3D.right,
    x: 0.30,
    y: -0.07,
    z: 0.05,
    width: 0.15,
    height: 0.43,
  ),
  MusclePatch3DSpec(
    id: 'spinalErectors.left',
    region: MuscleRegion.spinalErectors,
    surface: MuscleSurface3D.back,
    x: -0.065,
    y: -0.19,
    z: -0.29,
    width: 0.075,
    height: 0.64,
  ),
  MusclePatch3DSpec(
    id: 'spinalErectors.right',
    region: MuscleRegion.spinalErectors,
    surface: MuscleSurface3D.back,
    x: 0.065,
    y: -0.19,
    z: -0.29,
    width: 0.075,
    height: 0.64,
  ),
];

final Map<MuscleRegion, MuscleRegion3DMapping> muscleRegion3DMapping = {
  for (final region in MuscleRegion.values)
    region: MuscleRegion3DMapping(
      region: region,
      visualRegionIds: musclePatch3DSpecs
          .where((patch) => patch.region == region)
          .map((patch) => patch.id)
          .toList(growable: false),
      preferredYaw: _preferredYaw(region),
    ),
};

List<MuscleRegion> get unmappedMuscleRegions3D => MuscleRegion.values
    .where((region) => muscleRegion3DMapping[region]!.visualRegionIds.isEmpty)
    .toList(growable: false);

double _preferredYaw(MuscleRegion region) => switch (region) {
  MuscleRegion.lats ||
  MuscleRegion.upperBack ||
  MuscleRegion.midBack ||
  MuscleRegion.lowerBack ||
  MuscleRegion.rearDelts ||
  MuscleRegion.triceps ||
  MuscleRegion.hamstrings ||
  MuscleRegion.glutes ||
  MuscleRegion.spinalErectors => math.pi,
  MuscleRegion.sideDelts || MuscleRegion.obliques => -math.pi / 2,
  _ => 0,
};
