class ExerciseDefinition {
  final String name;
  final String bodyPart;
  final String equipment;

  const ExerciseDefinition({
    required this.name,
    required this.bodyPart,
    required this.equipment,
  });
}

const List<String> exerciseBodyParts = [
  '胸部',
  '背部',
  '腿部',
  '肩部',
  '手臂',
  '核心',
  '臀部',
  '全身/体能',
];

const List<ExerciseDefinition> exerciseCatalog = [
  // Chest
  ExerciseDefinition(name: '杠铃平板卧推', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '杠铃上斜卧推', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '杠铃下斜卧推', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃平板卧推', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃上斜卧推', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃下斜卧推', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃飞鸟', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '上斜哑铃飞鸟', bodyPart: '胸部', equipment: '自由重量'),
  ExerciseDefinition(name: '史密斯平板卧推', bodyPart: '胸部', equipment: '器械'),
  ExerciseDefinition(name: '史密斯上斜卧推', bodyPart: '胸部', equipment: '器械'),
  ExerciseDefinition(name: '器械推胸', bodyPart: '胸部', equipment: '器械'),
  ExerciseDefinition(name: '蝴蝶机夹胸', bodyPart: '胸部', equipment: '器械'),
  ExerciseDefinition(name: '双杠臂屈伸', bodyPart: '胸部', equipment: '徒手'),
  ExerciseDefinition(name: '标准俯卧撑', bodyPart: '胸部', equipment: '徒手'),
  ExerciseDefinition(name: '宽距俯卧撑', bodyPart: '胸部', equipment: '徒手'),
  ExerciseDefinition(name: '上斜俯卧撑', bodyPart: '胸部', equipment: '徒手'),
  ExerciseDefinition(name: '下斜俯卧撑', bodyPart: '胸部', equipment: '徒手'),
  ExerciseDefinition(name: '绳索夹胸', bodyPart: '胸部', equipment: '绳索'),
  ExerciseDefinition(name: '低位绳索夹胸', bodyPart: '胸部', equipment: '绳索'),
  ExerciseDefinition(name: '绳索推胸', bodyPart: '胸部', equipment: '绳索'),

  // Back
  ExerciseDefinition(name: '传统硬拉', bodyPart: '背部', equipment: '自由重量'),
  ExerciseDefinition(name: '相扑硬拉', bodyPart: '背部', equipment: '自由重量'),
  ExerciseDefinition(name: '杠铃俯身划船', bodyPart: '背部', equipment: '自由重量'),
  ExerciseDefinition(name: '潘德雷划船', bodyPart: '背部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃单臂划船', bodyPart: '背部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃胸托划船', bodyPart: '背部', equipment: '自由重量'),
  ExerciseDefinition(name: 'T 杆划船', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '高位下拉', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '宽握高位下拉', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '反握高位下拉', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '坐姿划船', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '单臂器械划船', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '胸托划船机', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '引体向上', bodyPart: '背部', equipment: '徒手'),
  ExerciseDefinition(name: '反手引体向上', bodyPart: '背部', equipment: '徒手'),
  ExerciseDefinition(name: '辅助引体向上', bodyPart: '背部', equipment: '器械'),
  ExerciseDefinition(name: '悬垂肩胛上拉', bodyPart: '背部', equipment: '徒手'),
  ExerciseDefinition(name: '直臂下拉', bodyPart: '背部', equipment: '绳索'),
  ExerciseDefinition(name: '面拉', bodyPart: '背部', equipment: '绳索'),
  ExerciseDefinition(name: '绳索单臂划船', bodyPart: '背部', equipment: '绳索'),
  ExerciseDefinition(name: '山羊挺身', bodyPart: '背部', equipment: '徒手'),

  // Legs
  ExerciseDefinition(name: '杠铃深蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '高杠深蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '前蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '暂停深蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '罗马尼亚硬拉', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '直腿硬拉', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '早安式', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '保加利亚分腿蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃箭步蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '行走箭步蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '高脚杯深蹲', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '单腿罗马尼亚硬拉', bodyPart: '腿部', equipment: '自由重量'),
  ExerciseDefinition(name: '腿举机', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '哈克深蹲', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '史密斯深蹲', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '史密斯箭步蹲', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '坐姿腿屈伸', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '俯卧腿弯举', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '坐姿腿弯举', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '站姿腿弯举', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '内收肌训练机', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '外展肌训练机', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '站姿提踵', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '坐姿提踵', bodyPart: '腿部', equipment: '器械'),
  ExerciseDefinition(name: '自重深蹲', bodyPart: '腿部', equipment: '徒手'),
  ExerciseDefinition(name: '跳深蹲', bodyPart: '腿部', equipment: '徒手'),
  ExerciseDefinition(name: '反向箭步蹲', bodyPart: '腿部', equipment: '徒手'),
  ExerciseDefinition(name: '单腿箱式深蹲', bodyPart: '腿部', equipment: '徒手'),
  ExerciseDefinition(name: '单腿提踵', bodyPart: '腿部', equipment: '徒手'),

  // Shoulders
  ExerciseDefinition(name: '杠铃站姿推举', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '杠铃坐姿推举', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃坐姿推举', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '阿诺德推举', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃侧平举', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃前平举', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃俯身飞鸟', bodyPart: '肩部', equipment: '自由重量'),
  ExerciseDefinition(name: '史密斯推举', bodyPart: '肩部', equipment: '器械'),
  ExerciseDefinition(name: '器械肩推', bodyPart: '肩部', equipment: '器械'),
  ExerciseDefinition(name: '反向蝴蝶机', bodyPart: '肩部', equipment: '器械'),
  ExerciseDefinition(name: '绳索侧平举', bodyPart: '肩部', equipment: '绳索'),
  ExerciseDefinition(name: '绳索前平举', bodyPart: '肩部', equipment: '绳索'),
  ExerciseDefinition(name: '绳索反向飞鸟', bodyPart: '肩部', equipment: '绳索'),
  ExerciseDefinition(name: '倒立撑', bodyPart: '肩部', equipment: '徒手'),
  ExerciseDefinition(name: '派克俯卧撑', bodyPart: '肩部', equipment: '徒手'),

  // Arms
  ExerciseDefinition(name: '杠铃弯举', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: 'EZ 杠弯举', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃交替弯举', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '锤式弯举', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '上斜哑铃弯举', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '集中弯举', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '牧师凳弯举', bodyPart: '手臂', equipment: '器械'),
  ExerciseDefinition(name: '绳索弯举', bodyPart: '手臂', equipment: '绳索'),
  ExerciseDefinition(name: '绳索锤式弯举', bodyPart: '手臂', equipment: '绳索'),
  ExerciseDefinition(name: '窄距卧推', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '杠铃颈前臂屈伸', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃颈后臂屈伸', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '仰卧臂屈伸', bodyPart: '手臂', equipment: '自由重量'),
  ExerciseDefinition(name: '绳索下压', bodyPart: '手臂', equipment: '绳索'),
  ExerciseDefinition(name: '反握绳索下压', bodyPart: '手臂', equipment: '绳索'),
  ExerciseDefinition(name: '绳索过顶臂屈伸', bodyPart: '手臂', equipment: '绳索'),
  ExerciseDefinition(name: '双杠臂屈伸', bodyPart: '手臂', equipment: '徒手'),
  ExerciseDefinition(name: '钻石俯卧撑', bodyPart: '手臂', equipment: '徒手'),

  // Core
  ExerciseDefinition(name: '平板支撑', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '侧平板支撑', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '卷腹', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '反向卷腹', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '仰卧单车', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '死虫式', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '鸟狗式', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '悬垂举腿', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '悬垂屈膝举腿', bodyPart: '核心', equipment: '徒手'),
  ExerciseDefinition(name: '健腹轮', bodyPart: '核心', equipment: '自由重量'),
  ExerciseDefinition(name: '俄罗斯转体', bodyPart: '核心', equipment: '自由重量'),
  ExerciseDefinition(name: '绳索卷腹', bodyPart: '核心', equipment: '绳索'),
  ExerciseDefinition(name: 'Pallof 抗旋转', bodyPart: '核心', equipment: '绳索'),
  ExerciseDefinition(name: '仰卧举腿', bodyPart: '核心', equipment: '徒手'),

  // Glutes
  ExerciseDefinition(name: '杠铃臀推', bodyPart: '臀部', equipment: '自由重量'),
  ExerciseDefinition(name: '单腿臀推', bodyPart: '臀部', equipment: '自由重量'),
  ExerciseDefinition(name: '哑铃臀推', bodyPart: '臀部', equipment: '自由重量'),
  ExerciseDefinition(name: '臀桥', bodyPart: '臀部', equipment: '徒手'),
  ExerciseDefinition(name: '单腿臀桥', bodyPart: '臀部', equipment: '徒手'),
  ExerciseDefinition(name: '绳索后踢腿', bodyPart: '臀部', equipment: '绳索'),
  ExerciseDefinition(name: '髋外展机', bodyPart: '臀部', equipment: '器械'),
  ExerciseDefinition(name: '45 度臀背挺身', bodyPart: '臀部', equipment: '器械'),
  ExerciseDefinition(name: '台阶上步', bodyPart: '臀部', equipment: '徒手'),
  ExerciseDefinition(name: '蚌式开合', bodyPart: '臀部', equipment: '徒手'),

  // Full body and conditioning
  ExerciseDefinition(name: '高翻', bodyPart: '全身/体能', equipment: '自由重量'),
  ExerciseDefinition(name: '抓举', bodyPart: '全身/体能', equipment: '自由重量'),
  ExerciseDefinition(name: '挺举', bodyPart: '全身/体能', equipment: '自由重量'),
  ExerciseDefinition(name: '推举借力', bodyPart: '全身/体能', equipment: '自由重量'),
  ExerciseDefinition(name: '壶铃摇摆', bodyPart: '全身/体能', equipment: '壶铃'),
  ExerciseDefinition(name: '壶铃高脚杯深蹲', bodyPart: '全身/体能', equipment: '壶铃'),
  ExerciseDefinition(name: '壶铃土耳其起身', bodyPart: '全身/体能', equipment: '壶铃'),
  ExerciseDefinition(name: '农夫行走', bodyPart: '全身/体能', equipment: '自由重量'),
  ExerciseDefinition(name: '雪橇推', bodyPart: '全身/体能', equipment: '器械'),
  ExerciseDefinition(name: '战绳', bodyPart: '全身/体能', equipment: '器械'),
  ExerciseDefinition(name: '划船机', bodyPart: '全身/体能', equipment: '器械'),
  ExerciseDefinition(name: '空中自行车', bodyPart: '全身/体能', equipment: '器械'),
  ExerciseDefinition(name: '波比跳', bodyPart: '全身/体能', equipment: '徒手'),
  ExerciseDefinition(name: '登山跑', bodyPart: '全身/体能', equipment: '徒手'),
  ExerciseDefinition(name: '开合跳', bodyPart: '全身/体能', equipment: '徒手'),
  ExerciseDefinition(name: '熊爬', bodyPart: '全身/体能', equipment: '徒手'),
];
